- build.xml
"ant test" compiles and run the unit tests.
> build.xml: Add target to run the tests

- src/com/amplitude/api/Amplitude.java
- src/com/amplitude/api/Constants.java
- src/com/amplitude/api/DatabaseHelper.java
- test/com/amplitude/api/AmplitudeTest.java
An app can now let a user choose whether to be included in tracking. From @curtisliu.
> Let users opt out of event logging

- build.xml
- src/com/amplitude/api/Amplitude.java
- src/com/amplitude/api/DatabaseHelper.java
Issue #9 (not #16 as reported in the commit) and issue #19 are fixed here.
> Fix two crashes

- CHANGELOG.md
- build.xml
Just change the version number in build.xml and run ```ant release```. It builds, sends all the packages to maven, and commits and tags to git. All that's left is logging into Sonatype and releasing the build.
> Automate releases

- src/com/amplitude/api/Constants.java
Just noticed version number in Constatns.java is not synced with version number in README
> Update version number in Constants.java to 1.4.4

- README.md
I had to stop and think because copy/pasting code didn't work :)
> Fix var name in revenue logging code.

- CHANGELOG.md
- src/com/amplitude/api/AmplitudeClient.java
- test/com/amplitude/api/AmplitudeTest.java
- test/com/amplitude/api/BaseTest.java
Add support for synchronous logging and offline mode. Useful for logging unhandled exceptions.
> Offline logging

- CHANGELOG.md
- src/com/amplitude/api/DeviceInfo.java
Catching more exception types when fetching most recent location: https://github.com/amplitude/Amplitude-Android/issues/166
> catch exceptions when fetching location

- src/main/java/com/amplitude/api/AmplitudeClient.java
- src/main/java/com/amplitude/api/Constants.java
- src/main/java/com/amplitude/unity/plugins/AmplitudePlugin.java
- src/test/java/com/amplitude/api/AmplitudeClientTest.java
- Added unit tests.
- Used demo app testing it's working properly.
> Add api to customize library

- src/main/java/com/amplitude/api/AmplitudeClient.java
Fixes #267 
I will do the full release cycle: Jenkins CI, new Maven/Sonatype release, new GitHub release
> Remove debug check

- src/main/java/com/amplitude/api/AmplitudeClient.java
- src/main/java/com/amplitude/api/MiddlewareExtra.java
- src/main/java/com/amplitude/api/MiddlewareRunner.java
- src/test/java/com/amplitude/api/AmplitudeClientTest.java
- src/test/java/com/amplitude/api/MiddlewareRunnerTest.java
- add logEvent(String eventType, JSONObject eventProperties, MiddlewareExtra extra) function signature
- MiddlewareExtra extends from HashMap<String, Object>
> fix: improvements for middleware

- src/main/java/com/amplitude/api/DeviceInfo.java
Adopt latest app set id apis
https://developer.android.com/training/articles/app-set-id
> fix: adopt latest app set id api

- src/main/java/com/amplitude/unity/plugins/AmplitudePlugin.java
- Add setGroup support in unity plugin
> feat: add setGroup support for unity plugin

- src/main/java/com/amplitude/api/AmplitudeClient.java
- fix: add status code check to response handlers
Related to: https://github.com/amplitude/Amplitude-iOS/pull/424
* Does your PR have a breaking change?:  No
> fix: add status code check to response handlers

- src/main/java/com/amplitude/api/AmplitudeClient.java
- src/main/java/com/amplitude/api/Constants.java
- src/main/java/com/amplitude/api/DatabaseHelper.java
- src/main/java/com/amplitude/api/IdentifyInterceptor.java
- src/test/java/com/amplitude/api/AmplitudeClientTest.java
- src/test/java/com/amplitude/api/BaseTest.java
- src/test/java/com/amplitude/api/DatabaseHelperTest.java
- src/test/java/com/amplitude/api/SessionTest.java
- Add identify interceptor
- update unit tests
> feat: add identify interceptor to reduce identify volume

- src/main/java/com/amplitude/api/IdentifyInterceptor.java
- src/test/java/com/amplitude/api/AmplitudeClientTest.java
- prevent setGroup from identify intercept
> fix: patch to prevent set group from identify intercept

- src/main/java/com/amplitude/api/IdentifyInterceptor.java
- src/test/java/com/amplitude/api/AmplitudeClientTest.java
- filter null user property value in identify interceptor
> fix: filter null value in identify user properties

- src/main/java/com/amplitude/api/IdentifyInterceptor.java
- src/test/java/com/amplitude/api/AmplitudeClientTest.java
- src/test/java/com/amplitude/api/DatabaseRecoveryTest.java
- update to intercept identify only
> fix: update identify interceptor to identify only

- .github/workflows/release.yml
- release.config.js
> chore: add release action

- .github/workflows/release.yml
- release.config.js
> chore: update release action

- release.config.js
> chore: fix release replacement config

- .github/workflows/codeql-analysis.yml
- .github/workflows/test.yml
* Added CI tests for all PRs
* Updated CodeQL to v2 to fix errors from V1
> Amp 77104 sdk add ci tests fix codeql action

- .github/workflows/jira-issue-create.yml
* update issues workflow to create ticket in AMP
> chore: update issues workflow to create ticket in AMP

- .github/workflows/release.yml
Workaround for
https://github.com/jpoehnelt/semantic-release-replace-plugin/issues/221
> Fix semantic release replace plugin
