amplitude/Amplitude-Android

src/com/amplitude/api/DeviceInfo.java, test/com/amplitude/api/DeviceInfoTest.java
Location handling has a couple of extreme edge cases that produce null values. Handle those cases to avoid crashing.
Fix for #16.
=> Handle null edge cases in location request

README.md
Included the instruction to import the amplitude library for projects
using gradle, the new build tool recommended by Google to create
android projects.
Signed-off-by: Joao Trindade <trindade.joao@gmail.com>
=> Added instructions for import in gradle files

CHANGELOG.md, src/com/amplitude/api/AmplitudeClient.java, src/com/amplitude/api/Constants.java, test/com/amplitude/api/BaseTest.java, test/com/amplitude/api/UpgradePrefsTest.java
Also, move preference data from the old package name scheme to the new so that no data is lost on upgrades.
=> Don't use reflection to find api package name.

CHANGELOG.md, src/com/amplitude/api/AmplitudeClient.java, test/com/amplitude/api/AmplitudeTest.java, test/com/amplitude/api/SessionTest.java
This is caused by onEnterForeground which can send start/end session events on main thread. The fix is to start new session if necessary on the background thread. Start new session should still log events synchronously (in the case where logging an event starts a new session, we want the start/end session events to be sent before the logged event).
It should be okay to toggle the inForeground boolean on the background thread, since log event is the only function that uses it, and that should be called on the background thread.
=> Don't fetch device ID on main thread

CHANGELOG.md, pom.xml, src/com/amplitude/api/AmplitudeClient.java, src/com/amplitude/api/DeviceInfo.java, test/com/amplitude/api/DeviceInfoTest.java
The standard way to check if GPS enabled is this:
```
int statusCode = GooglePlayServicesUtil.isGooglePlayServicesAvailable(context);
if (statusCode == ConnectionResult.SUCCESS) {
...
}
```
Note: You will notice that on Line 212 I do statusCode == 0, instead of ConnectionResult.SUCCESS, because ConnectionResult is another gms library and I don't want to load that through reflection just to get the value of [success, which is just 0 anyways](https://developers.google.com/android/reference/com/google/android/gms/common/ConnectionResult.html#SUCCESS).
I do have a test (testGPSEnabled), which does use ConnectionResult.SUCCESS, which will break and let us know if Google ever decides to change the mapped value. I also tested it on the Android demo (with GPS enabled and disabled).
=> Log if Google Play Services enabled in api properties['gps_enabled']

CHANGELOG.md, README.md, src/com/amplitude/api/AmplitudeClient.java, src/com/amplitude/api/Constants.java, src/com/amplitude/api/Identify.java, test/com/amplitude/api/IdentifyTest.java
1. Add $append operation
2. Deprecate existing Identify.set and Identify.setOnce that allow Object type inputs for the value. We explicitly only want people to pass in String, boolean, float, int, double, long, JSONArray, JSONObject.
3. In translating setUserProperties calls to an Identify object, we still want some form of set that allows Object type inputs, so I added a package private Identify.setUserProperty. I was also considering adding some sort of Identify.initWithUserProperties(JSONObject) method, but we would still want to do duplicate checking, so it makes sense just to keep the set.
PTAL at the API changes @curtisliu
=> Append operation

CHANGELOG.md, README.md, src/com/amplitude/api/Amplitude.java, src/com/amplitude/api/AmplitudeClient.java, src/com/amplitude/api/AmplitudeUtils.java, src/com/amplitude/api/Constants.java, src/com/amplitude/api/DatabaseHelper.java, test/com/amplitude/api/AmplitudeClientTest.java, test/com/amplitude/api/AmplitudeTest.java, test/com/amplitude/api/BaseTest.java, test/com/amplitude/api/DatabaseHelperTest.java, test/com/amplitude/api/InitializeTest.java, test/com/amplitude/api/UpgradePrefsTest.java
Allowing multiple apps on Android SDK is way more straightforward than on JS SDK. 
Android SDK is already setup with Amplitude / AmplitudeClient classes, with Amplitude.getInstance() a standard part of our API. Just need to update Amplitude to manage a map of different instance names to different AmplitudeClient instances. Like with JS SDK, if the instance name is blank or null, then we default to a "$defaultInstance" name.
All events and a few meta data + settings are stored in a Sqlite db file. To separate these out for each instance, we give each instance its own Sqlite db file, and the name of the db file is appended with that instance's apiKey for uniqueness. This does mean that the AmplitudeClient instance needs to be initialized with the apiKey before being able to interact with …
=> Allow multiple apps

CHANGELOG.md, pom.xml, src/com/amplitude/api/AmplitudeClient.java, src/com/amplitude/api/PinnedAmplitudeClient.java, test/com/amplitude/api/AmplitudeClientTest.java, test/com/amplitude/api/BaseTest.java, test/com/amplitude/api/InitializeTest.java, test/com/amplitude/api/PinningTest.java
PR in response to: https://github.com/amplitude/Amplitude-Android/issues/73
Few changes:
1. Formencodingbuilder has been replaced with Formbody.builder
2. The new OkhttpClient is stateless, no more getters and setters. To have a custom SSLSocketFactory you need to build a new OkHttpClient instance using the builder. This has to be done in the initialize method, no longer need a separate makeEventUploadPostRequest method
3. Allow multiple named instances of PinnedAmplitudeClient
Note this does increase the size of amplitude-android-with-dependencies from 411kb to 488kb
=> Update to OKHttp v3

CHANGELOG.md, src/com/amplitude/api/AmplitudeClient.java, src/com/amplitude/api/PinnedAmplitudeClient.java
Addresses this crash: https://github.com/amplitude/Amplitude-Android/issues/97
Error occurs because some of the AmplitudeClient methods are private, and PinnedAmplitudeClient.enableForegroundTracking uses the wrong instance
Thanks to @dmnugent80 for the fix
=> Stop using `instance` in AmplitudeClient and use `this` instead

CHANGELOG.md, src/com/amplitude/api/DeviceInfo.java
According to https://github.com/amplitude/Amplitude-Android/issues/104, it seems that trying to fetch the location information might sometimes fail on select devices. We want to catch the exception and make sure it doesn't crash the app/SDK.
Not sure why that security exception is occurring though, fetching location information shouldn't need anything other than location permissions. It seems to be isolated to select Android devices
=> Catch security exceptions thrown during getProviders and location lookup

src/com/amplitude/api/AmplitudeClient.java, src/com/amplitude/api/DeviceInfo.java, test/com/amplitude/api/AmplitudeClientTest.java, test/com/amplitude/api/DeviceInfoTest.java
Getting the advertiser ID currently only supports devices with Google play services. This adds support for getting the advertising ID from an Amazon device.
[Amazon advertising ID docs](https://developer.amazon.com/public/solutions/devices/fire-tablets/app-development/using-the-advertising-id-in-your-app)
=> Add support for Amazon advertising ID

CHANGELOG.md, src/com/amplitude/api/AmplitudeClient.java, test/com/amplitude/api/AmplitudeClientTest.java, test/com/amplitude/api/InitializeTest.java
Addresses https://github.com/amplitude/Amplitude-Android/issues/113
With this [change](https://github.com/amplitude/Amplitude-Android/pull/109/files) that went out in v2.8.0, I forgot to also update `setOptOut` to run on background thread.
=> setOptOut on background thread

src/com/amplitude/api/AmplitudeClient.java
Otherwise, can't set location listening reliably -- likely to throw exception (see below), since init is on background thread, and no way to get callback when init completed, in order to enable/disable location listening.
```
java.lang.IllegalStateException: Must initialize before acting on location listening.
at com.amplitude.api.AmplitudeClient.disableLocationListening(AmplitudeClient.java:336)
```
=> set location listening on background thread

CHANGELOG.md, src/com/amplitude/api/DeviceInfo.java
Sometimes the Android device GPS can rarely give bad values for Lat / Lon: https://github.com/amplitude/Amplitude-Android/issues/119 (for example 1.02E7 when Lat values need to be between -90 and 90). The Android geocoder will throw IllegalArgumentExceptions in those cases. We just need to catch those exceptions.
=> Handle illegal arguement exception for bad lat lon values

CHANGELOG.md, src/com/amplitude/api/AmplitudeClient.java, src/com/amplitude/api/CursorWindowAllocationException.java, src/com/amplitude/api/DatabaseHelper.java, test/com/amplitude/api/AmplitudeClientTest.java, test/com/amplitude/api/BaseTest.java, test/com/amplitude/api/DatabaseHelperTest.java, test/com/amplitude/api/InitializeTest.java, test/com/amplitude/api/SessionTest.java
This addresses: https://github.com/amplitude/Amplitude-Android/issues/42. We believe that our SDK correctly closes cursors, which would mean that these CursorWindowAllocationExceptions are caused by the app running out of memory, not something in our SDK's control. That being said, the crash still originates from our SDK, and so we should attempt to catch it and gracefully handle it, instead of crashing the app.
Our SDK uses cursors when fetching unsent events/identifies and key/value pairs. We need to catch the exception in these 3 primary use cases:
1. Fetching unsent events/identifies for upload
* If the fetch fails, then we can simply defer the upload, and try again later maybe when the app has more free memory
2. Fetching the userId/deviceId during initialization
* It is crucial that …
=> Gracefully catch and handle CursorWindowAllocationException

CHANGELOG.md, README.md, src/com/amplitude/api/AmplitudeClient.java, test/com/amplitude/api/SessionTest.java
Some customers want to log identify events while their app is in the background, without triggering start/end session events. We can expose the outOfSession boolean as an argument.
=> identify with outOfSession

CHANGELOG.md, src/com/amplitude/api/AmplitudeClient.java, src/com/amplitude/api/DeviceInfo.java
DeviceInfo.generateUUID() should also be a static method, and should not require AmplitudeClient.deviceInfo to be initialized first
=> Regenerate device id should be run on bg thread

CHANGELOG.md, src/com/amplitude/api/AmplitudeClient.java, src/com/amplitude/api/DatabaseHelper.java, test/com/amplitude/api/AmplitudeClientTest.java, test/com/amplitude/api/DatabaseHelperTest.java
Android SDK crashes when loading events from db table if there's a null event string.
* check event string is not null before deserializing - this should stop the crashes
* it's important to note that the metadata state is still okay (like if it logged a null event, then lastEventId will be incremented, but it can safely skip over the null event when fetching)
* if valid events are logged after the null event, they still get sent correctly
* event servers can handle payloads with empty event lists (although if there are no events to send the SDK won't even make a request out)
* Added some more logging around JSON serialization errors - I think that's how null events are getting added to the table
* Only save the event string if it serializes properly
=> Handle null event strings

CHANGELOG.md, src/com/amplitude/api/DatabaseHelper.java
Should handle weird database interactions on certain Android devices (Fairphone and LG) with buggy database implementations.
Addresses https://github.com/amplitude/Amplitude-Android/issues/131 and https://github.com/amplitude/Amplitude-Android/issues/133
=> handle exceptions when reading from database

src/com/amplitude/api/DeviceInfo.java
I've come across exceptions in `getCarrier` when initializing the Amplitude client. This change handles this in the same way as `getCountryFromNetwork`.
=> Catch more exceptions from TelephonyManager

CHANGELOG.md, src/com/amplitude/api/AmplitudeClient.java
`setUserProperties` should follow `logEvent` in that the userProperties are cloned (shallow) on the main thread, before being passed to the logic on the background thread. That prevents ConcurrentModificationExceptions. Also, since setUserProperties calls `identify` which handles the background logic, there's no need to run any of the function logic on the background thread.
=> copy userproperties on main thread

CHANGELOG.md, src/com/amplitude/api/Amplitude.java, src/com/amplitude/api/AmplitudeClient.java, src/com/amplitude/api/Constants.java, src/com/amplitude/api/DatabaseHelper.java, src/com/amplitude/api/PinnedAmplitudeClient.java, src/com/amplitude/api/Utils.java, test/com/amplitude/api/AmplitudeClientTest.java, test/com/amplitude/api/AmplitudeTest.java, test/com/amplitude/api/BaseTest.java, test/com/amplitude/api/DatabaseHelperTest.java, test/com/amplitude/api/PinningTest.java
Feature parity with our iOS / JS SDKs.
Instead of 1 static instance of the AmplitudeClient, we have the Amplitude parent class maintain a map from instance name to AmplitudeClient. 
New calling convention: `Amplitude.getInstance("app name").<function>`
Existing calls to `Amplitude.getInstance()` will get mapped to the default instance (we catch null instance names and substitute with "$default_instance"`.
Instance names are case insensitive by design choice
Need to add an instance map in 3 places: Amplitude parent class, DatabaseHelper class (each instance needs its own separate database file, the default instance keeps the existing database file so we don't need any migration code), PinnedAmplitudeClient
=> add support for multiple instances

src/com/amplitude/api/AmplitudeClient.java, test/com/amplitude/api/AmplitudeClientTest.java
Adding ability to override platform value. This override has to happen in `initialize` before any of the session events get logged.
=> Custom platform initialize

src/com/amplitude/api/AmplitudeClient.java, test/com/amplitude/api/SessionTest.java
Expose a public `setUserIdAndStartNewSession` method that is basically https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/AmplitudeClient.java#L1108-L1120 and sets the userId between sending the start and end session events.
=> Set user id new session

CHANGELOG.md, src/com/amplitude/api/Constants.java
If an event upload succeeds, we then try to upload any remaining unsent events, in batches of 100. Depending on how big the event payloads are and the amount of memory on the device, this could cause an OOM crash. Decreasing the max batch size to 50 should be safe.
=> lower event upload max batch size to 50

CHANGELOG.md, src/com/amplitude/api/AmplitudeClient.java
Customer request to make `startNewSessionIfNeeded` public: https://github.com/amplitude/Amplitude-iOS/issues/180
Tested calling the method in Android Demo
This is the Android version of: https://github.com/amplitude/Amplitude-iOS/pull/189
=> make start new session if needed public

README.md
The Changelog link in the Readme is updated to the Wiki link.
=> Fix Changelog link in Readme

src/main/java/com/amplitude/api/AmplitudeClient.java, src/main/java/com/amplitude/api/Constants.java, src/main/java/com/amplitude/api/TrackingOptions.java, src/main/java/com/amplitude/unity/plugins/AmplitudePlugin.java
Tested: events went through, not affected.
=> Able to track `api_level` as a device property

src/main/AndroidManifest.xml, src/main/java/com/amplitude/api/DeviceInfo.java, src/main/java/com/amplitude/api/Utils.java, src/test/java/com/amplitude/api/DeviceInfoTest.java
We can't assume every app will need location permission. For kids app, that is suggested turned on. Or for some app which doesn't require location at all. (e.g. QRCode scanner, utility apps)
Test:
API 29
- Tested with no permission in manifest, and verified location logic was not called. App worked properly.
- Tested with permissions in manifest but not granted, and verified location logic was not called. App worked properly.
- Tested with permissions in manifest and granted, and verified location logic was executed. App worked properly.
API 22
- Tested with no permission in manifest, and verified location logic was not called. App worked properly.
- Tested with permissions in manifest, and verified location logic was executed. App worked properly.
=> Remove location permission declaration from manifest file

src/main/java/com/amplitude/api/AmplitudeClient.java, src/main/java/com/amplitude/api/DeviceInfo.java, src/test/java/com/amplitude/api/DeviceInfoTest.java
Once location is cached, you won't be able to disable location listening at all. However, disabling location listening will result crash if it's called before initialization.
#240
=> Fix - unable to disable location listening at the beginning

src/main/java/com/amplitude/unity/plugins/AmplitudePlugin.java
Note that the current Android AmplitudeClient API uses
```
public AmplitudeClient setEventUploadPeriodMillis(int eventUploadPeriodMillis) {
this.eventUploadPeriodMillis = eventUploadPeriodMillis;
return this;
}
```
=> Expose event upload millis API for use in Unity

src/main/java/com/amplitude/unity/plugins/AmplitudePlugin.java
Recently, GitHub changed the name of the default `master` branch to `main`. I agree with GitHub's change in support of social justice. However, this change broke our Jenkins/Docker CI job, see [here](https://github.com/amplitude/deploy/blob/6c21781b2ea4292d34ea06b299709f60d7026c38/utils/sdk/android/release.sh#L68). 
This will allow us to build on Jenkins again for a [customer feature request](https://github.com/amplitude/unity-plugin/pull/58).
=> Master <- Main

src/main/java/com/amplitude/api/AmplitudeClient.java
Will handle fixing the tests later. There are too many tests to fix right now and I want to unblock the customer.
=> Quick fix to remove sharedPreferences call/legacy migration

src/main/java/com/amplitude/api/DatabaseHelper.java
Fixes #283 
The underlying android exception CursorWindowAllocationException was not correctly getting converted to our own implementation of that exception because its message string was formatted differently. This led to an unhandled RuntimeException being thrown. 
This PR also checks for the alternate formatting before converting the exception.
=> bug: add more error handling for cursor allocation exception

build.gradle, src/main/java/com/amplitude/api/AmplitudeClient.java, src/main/java/com/amplitude/api/Constants.java, src/main/java/com/amplitude/api/DeviceIdType.java, src/main/java/com/amplitude/api/DeviceInfo.java, src/main/java/com/amplitude/api/TrackingOptions.java, src/main/java/com/amplitude/unity/plugins/AmplitudePlugin.java, src/test/java/com/amplitude/api/TrackingOptionsTest.java
Add app set id support
add app set id get function (Use reflection, tested on emulator with no package installed and package installed, can get the app set id in later case)
support useAppSetIdForDeviceId (Use synchronous to align on the pattern as of today.)
add app set id in api properties
add app set id in tracking options
expose useAppSetIdForDeviceId and disableAppSetId in plugin
[Android doc](https://developer.android.com/training/articles/app-set-id#java)
=> Appsetid support

src/main/java/com/amplitude/api/DeviceInfo.java
Summary
1. Handle SecurityException thrown by calling Geocoder.getFromLocation()
Checklist
[X ] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-Java/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
Does your PR have a breaking change?: no
=> fix: App Crash due to SecurityException

build.gradle
Potential solution for #320 
Mark analytics-connector dependency as not optional (required) in pom
=> fix: mark connector package as required in pom

src/main/java/com/amplitude/api/DeviceInfo.java, src/test/java/com/amplitude/api/DeviceInfoTest.java
In case of changing the app language programmatically it also needs to call `Locale.setDefault()` because `Locale.getDefault()` is  used in many android SDK places. So it's better to use `Resources.getSystem().getConfiguration().getLocales() ` to detect the device language.
=> fixed detecting device language

src/main/java/com/amplitude/api/AmplitudeClient.java, src/main/java/com/amplitude/api/Constants.java, src/main/java/com/amplitude/api/IngestionMetadata.java, src/test/java/com/amplitude/api/AmplitudeClientTest.java, src/test/java/com/amplitude/api/IngestionMetadataTest.java
- feat: add ingestion_metadata field
Add this option in the configuration, which can be used in the library wrapper/code generation/dynamic loading cases, for setting the `ingestion_metadata` information.
=> feat: add ingestion_metadata field

README.md
Update badge in doc to only reflect 2.x version
=> doc: update badge to use 2.x version

src/main/java/com/amplitude/api/AmplitudeClient.java, src/test/java/com/amplitude/api/AmplitudeClientTest.java
When making an event upload request, check the response code === 200 instead of checking the string response, in order to support the usage of a custom amplitude proxy.
https://github.com/amplitude/Amplitude-Android/issues/348
https://github.com/amplitude/Amplitude-JavaScript/pull/572
=> fix: check response code when response code is 200

src/main/java/com/amplitude/api/IdentifyInterceptor.java, src/test/java/com/amplitude/api/AmplitudeClientTest.java
When user id or device id update, transfer the identify events intercepted to prevent information mix.
=> fix: catch the case in intercept for identity update

src/main/java/com/amplitude/api/AmplitudeClient.java, src/test/java/com/amplitude/api/SessionTest.java
inForeground reads/writes moved to main thread.
The session logic has some differences compared to Amplitude-iOS. I would re-write session logic to match Ampltude-Kotlin/Amplitude-Swift implementation.
For some reason I have a few issues with the Amplitude-Android project on my machine with latest Android Studio:  unresolved identifiers in test files, `./gradlew build` fails with `204 tests completed, 35 failed` (but in Android Studio UI all tests are green).
=> fix: move inForeground reads/writes to main thread

.github/workflows/release.yml
Author released a new version `@google/semantic-release-replace-plugin@1.2.4` with a fix to ESM errors
=> chore: revert to @google/semantic-release-replace-plugin@1

.github/workflows/release.yml
* chore: `@google/semantic-release-replace-plugin` `1.2.4` doesn't seem to work, fixing to `1.2.0`
=> chore: 1.2.4 doesn't seem to work, fixing to 1.2.0

src/main/java/com/amplitude/api/DatabaseHelper.java, src/main/java/com/amplitude/api/IdentifyInterceptor.java
https://github.com/amplitude/Amplitude-Android/blob/main/CHANGELOG.md#2100-oct-12-2016 
```
Catch and handle CursorWindowAllocationException thrown when the SDK is querying from > the SQLite DB when app memory is low.
If the exception is caught during initialize, then it is treated as if initialize was > never called.
If the exception is caught during the uploading of unsent events, then the upload is deferred to a later time.
```
https://github.com/amplitude/Amplitude-Android/blob/main/src/main/java/com/amplitude/api/AmplitudeClient.java#L444 
```
} catch (CursorWindowAllocationException e) {  // treat as uninitialized SDK
logger.e(TAG, String.format(
"Failed to initialize Amplitude SDK due to: %s", e.getMessage()
));
client.apiKey = null;
}
```` …
=> fix: try to reduce sqlite cursor memory usage

src/main/java/com/amplitude/api/AmplitudeClient.java
We are [still getting long sessions for some customers in Flutter on Android](https://amplitude.atlassian.net/browse/AMP-76734?focusedCommentId=198409) after the other session fixes.
This change aims to handle the hypothetical case where an event is tracked before the `runOnLogThread(new Runnable()` executes.
That scenario would lead the event being "in foreground" which would extend the existing session.
Maybe it is also possible to move setting `inForeground` to the first line of the onEnterForeground Runnable? wdyt @falconandy?
```diff
void onEnterForeground(final long timestamp) {
-        inForeground = true;
runOnLogThread(new Runnable() {
@Override
public void run() {
+             inForeground = true;
```
https://github.com/amplitude/Amplitude-Android/pull/362/files
=> fix: try to correctly handle session change for race condition

src/main/java/com/amplitude/api/AmplitudeClient.java
Fixes: https://github.com/amplitude/experiment-android-client/issues/53
Issue was that it's possible that the experiment SDK tracks an event before the identify interceptor is set up.
=> fix: move identifyInterceptor before eventBridge receiver is set

.github/workflows/release.yml, .github/workflows/test.yml, src/main/java/com/amplitude/api/AmplitudeClient.java, src/main/java/com/amplitude/api/MiddlewareExtended.java, src/main/java/com/amplitude/api/MiddlewareRunner.java, src/test/java/com/amplitude/api/MiddlewareRunnerTest.java
[AMP-97797]
Updates to core SDK to support session replay middleware
* Add AmplitudeClient.getOptOut() to allow SR middleware to use client optOut value
* Add MiddlewareExtended and MiddlewareRunner.flush() to allow automatic flushing of SR events on `flushEventsOnClose=true` and `amplitude.uploadEvents()`
[AMP-97797]: https://amplitude.atlassian.net/browse/AMP-97797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: middleware session replay integration

src/main/java/com/amplitude/api/AmplitudeClient.java
MiddlewareRunner.flush() wasn't always called on updateServer (there are multiple locations updateServer is called)
=> fix: always run middleware flush on updateServer
